### ISSUE TITLE
Export de données depuis la partie résultats

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#7]
L'export de données ne fonctionne pas (testé en csv et shp) - outil téléchargement dans la partie droite de l'écran
![Export](https://user-images.githubusercontent.com/61181043/74728460-16fa2480-5243-11ea-8433-1bead0792e83.jpg)

**Comment by jpm-cbna** [comment]
Le message d'erreur correspondant côté serveur :+1: 

```
/home/geonat/www/geonature_v2.2.1/backend/venv/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_sensitivity, 'SENSIBILITE'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/home/geonat/www/geonature_v2.2.1/backend/venv/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_observation_status, 'STATUT_OBS'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/home/geonat/www/geonature_v2.2.1/backend/venv/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_blurring, 'DEE_FLOU'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/home/geonat/www/geonature_v2.2.1/backend/venv/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_info_geo_type, 'TYP_INF_GEO'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/home/geonat/www/geonature_v2.2.1/backend/venv/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: 'CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature, mnemonique_type)) NOT VALID'
  util.warn("Could not parse CHECK constraint text: %r" % src)
/home/geonat/www/geonature_v2.2.1/backend/venv/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK ((taxonomie.check_is_group2inpn((group2_inpn)::text) OR ((group2_inpn)::text = '0'::text))) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/home/geonat/www/geonature_v2.2.1/backend/venv/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK ((taxonomie.check_is_regne((regne)::text) OR ((regne)::text = '0'::text))) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
Exception on /synthese/export_observations [POST]
Traceback (most recent call last):
  File "/home/geonat/www/geonature_v2.2.1/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/geonat/www/geonature_v2.2.1/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/geonat/www/geonature_v2.2.1/backend/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/geonat/www/geonature_v2.2.1/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/geonat/www/geonature_v2.2.1/backend/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/geonat/www/geonature_v2.2.1/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonat/www/geonature_v2.2.1/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonat/www/geonature_v2.2.1/backend/geonature/core/gn_permissions/decorators.py", line 95, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/geonat/www/geonature_v2.2.1/backend/geonature/core/gn_synthese/routes.py", line 344, in export_observations_web
    with_generic_table=True,
  File "/home/geonat/www/geonature_v2.2.1/backend/geonature/core/gn_synthese/utils/query.py", line 66, in filter_query_with_cruved
    model.id_synthese.in_(sub_query_observers),
AttributeError: 'Table' object has no attribute 'id_synthese'
[2020-02-21 16:11:09 +0100] [17656] [INFO] 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by jpm-cbna** [comment]
Le problème provoquant le bug ci-dessous a été corrigé dans la version 2.3.0 de GeoNature.
J'ai corrigé manuellement le problème sur le serveur.

Malheureusement, un second problème survient sur les gros export liés au temps maximum d’exécution des requêtes Gunicorn:
```
[2020-02-25 12:01:56 +0100] [3782] [CRITICAL] WORKER TIMEOUT (pid:3792)
```
Pour  résoudre ce 2nd problème, il faut modifier le temps d’exécution par défaut dans le fichier `backend/gunicorn_start.sh` => `--timeout 30`

Le 3ème problème survient avec le contenu du fichier exporté qui est vide...

**Comment by jpm-cbna** [comment]
Le 3ème problème survient avec le contenu du fichier exporté qui est vide...

Ce problème est dû au droit insuffisant de l'utilisateur vis à vis de l'action "Export".

Pour pouvoir "voir" et "exporter" les données de manière équivalente, il est nécessaire de mettre la même portée pour l'actin "Lire" et "Exporter" du CRUVED. Dans notre cas pour le test, c'est la valeur "3" (= "Toutes les données") qu'il faut attribuer. L'attribution se fait au groupe "En poste" dans lequel tous les nouveaux utilisateurs arrivent.
